# Generated by Django 5.2.9 on 2025-12-26 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("_api_", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="current_price_db",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-calculated: sale_price if available, otherwise base_price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("context", models.JSONField(default=dict)),
                ("detected_intent", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recommended_projects",
                    models.ManyToManyField(blank=True, to="_api_.project"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("ai", "AI Response"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="_api_.aichatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("multiple_accounts", "Multiple Accounts"),
                            ("fake_reviews", "Fake Reviews"),
                            ("suspicious_purchase", "Suspicious Purchase"),
                            ("abuse_pattern", "Abuse Pattern"),
                            ("spam_activity", "Spam Activity"),
                            ("fraudulent_payment", "Fraudulent Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("action_taken", models.CharField(blank=True, max_length=100)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("estimated_duration", models.IntegerField(default=0)),
                ("difficulty_progression", models.JSONField(default=list)),
                ("generated_by", models.CharField(default="ai", max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("completed", models.BooleanField(default=False)),
                ("progress", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("learning_objectives", models.JSONField(default=list)),
                ("prerequisites", models.JSONField(default=list)),
                ("estimated_hours", models.IntegerField(default=10)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="_api_.learningpath",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="_api_.project"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("learning_path", "project")},
            },
        ),
        migrations.AddField(
            model_name="learningpath",
            name="projects",
            field=models.ManyToManyField(
                through="_api_.LearningPathProject", to="_api_.project"
            ),
        ),
        migrations.CreateModel(
            name="ProjectEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_embedding", models.JSONField(default=list)),
                ("feature_embedding", models.JSONField(default=list)),
                ("category_vector", models.JSONField(default=list)),
                ("technology_vector", models.JSONField(default=list)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("similar_projects", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="_api_.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_weights", models.JSONField(default=dict)),
                ("technology_weights", models.JSONField(default=dict)),
                ("difficulty_preference", models.FloatField(default=0.5)),
                ("price_sensitivity", models.FloatField(default=0.5)),
                ("feature_weights", models.JSONField(default=dict)),
                ("learning_style", models.JSONField(default=dict)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("needs_recalculation", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_vector",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_score", models.FloatField(default=0.0)),
                ("collaborative_score", models.FloatField(default=0.0)),
                ("popularity_score", models.FloatField(default=0.0)),
                ("personalization_score", models.FloatField(default=0.0)),
                ("final_score", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("content_based", "Content Based"),
                            ("collaborative", "Collaborative Filtering"),
                            ("trending", "Trending"),
                            ("similar_users", "Similar Users"),
                            ("complementary", "Complementary"),
                            ("personalized", "Personalized"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="_api_.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-final_score", "position"],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("results_count", models.IntegerField(default=0)),
                ("clicked_results", models.JSONField(blank=True, default=list)),
                ("search_filters", models.JSONField(blank=True, default=dict)),
                ("detected_intent", models.CharField(blank=True, max_length=100)),
                ("query_embedding", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="Dapi__searc_user_id_8062f4_idx",
                    ),
                    models.Index(fields=["query"], name="Dapi__searc_query_dc49c0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("search_query", models.TextField(blank=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="_api_.category",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="_api_.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="Dapi__userb_user_id_437ee8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="Dapi__userb_created_87eebc_idx"
                    ),
                ],
            },
        ),
    ]
